name: Docker Build

on:
  push:
    branches:
      - main  # 每次 push 到 main 就會自動執行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build python-app image
      run: |
        cd python-app
        docker build -t nolonger89/2025cloud:python-app .

    - name: Build nginx-site image
      run: |
        cd ../nginx-site
        docker build -t nolonger89/2025cloud:nginx-site .