name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # 每次 push 到 main 就觸發

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push python-app
      run: |
        cd python-app
        docker build -t nolonger89/2025cloud:python-app .
        docker push nolonger89/2025cloud:python-app

    - name: Build and push nginx-site
      run: |
        cd ../nginx-site
        docker build -t nolonger89/2025cloud:nginx-site .
        docker push nolonger89/2025cloud:nginx-site